services:
  db:
    image: postgres:16-alpine
    container_name: kanban-db-dev
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: kanban_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data_dev

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kanban-api-dev
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://sa:123456@db:5432/kanban_db
      PORT: 3000
    volumes:
      - .:/app               # hot reload no código
      - /app/node_modules   # evita sobrescrever node_modules do container
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate dev && npm run dev"

volumes:
  postgres_data_dev: