services:
  db:
    image: postgres:16-alpine
    container_name: kanban-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: kanban_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: kanban-api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://sa:123456@db:5433/kanban_db
      PORT: 3000
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/server.js"

volumes:
  postgres_data: